#!/usr/bin/perl

use Modern::Perl;
use FartD;
use YAML;
our $run = 1;

my $conf = YAML::LoadFile("/etc/fartd/fartd.conf");
while ($run) {
	my $sleepfor = int(rand($conf->{max_wait}-$conf->{min_wait}))+$conf->{min_wait};
	my $index = int(rand(scalar(@{$conf->{sounds}})));
	my $wtp = $conf->{sounds}->[$index];
	sleep($sleepfor);
	if (-f $wtp) {
		FartD::playwav($wtp);
	} else {
		say STDERR "$wtp is not there dude what the hell";
	}
}

exit;




