#!/usr/bin/perl

use Modern::Perl;
use Proc::Daemon;
use FartD::SDL;
use YAML;
our $run = 1;

#$SIG{TERM} = \&signal;
#$SIG{INT} = \&signal;
my $conf = YAML::LoadFile("/etc/fartd/fartd.conf");
open(LOG,">>",$conf->{log});
while ($run) {
	my $sleepfor = int(rand($conf->{max_wait}-$conf->{min_wait}))+$conf->{min_wait};
	say STDERR "Waiting $sleepfor seconds.";
	sleep($sleepfor);	
	my $index = int(rand(scalar(@{$conf->{sounds}})));
	my $wtp = $conf->{sounds}->[$index];
	say STDERR sprintf("index %d playing %s",$index,$wtp);

	if (-f $wtp) {
		FartD::SDL::playwav($wtp);
	} else {
		say STDERR "$wtp is not there dude what the hell";
	}
}

sub signal {
	$run=0;
}

exit;




